FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install && \
    npx prisma generate

COPY . .

EXPOSE 3001

CMD ["npm", "run", "start:dev"]